{% extends "app/base.phtml" %}

{% block content %}
	
	<h3>Change password</h3>
	
	<form action="{{ path_for('user.password') }}" method="post" autocomplete="off" novalidate>
		
		<div class="{{ errors.password ? 'has-error' }}">
			<label for="password">Current password</label>
			<input type="password" name="password">
			{% if errors.password %}
				<p>{{ errors.password | first }}</p>
			{% endif %}
		</div>
		
		<div class="{{ errors.password_new ? 'has-error' }}">
			<label for="password_new">New password</label>
			<input type="password" name="password_new">
			{% if errors.password_new %}
				<p>{{ errors.password_new | first }}</p>
			{% endif %}
		</div>
		
		{{ csrf.field | raw }}
		
		<button type="submit">Change</button>
		
	</form>
	
{% endblock content %}
