<!doctype html>
<html lang="en" dir="ltr">
<head>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	
	<title>{% block head_title %}{% endblock head_title %}{% block head_title_extra %} | Name of Website | Additional Info{% endblock head_title_extra %}</title>
	<meta name="description" content="{% block head_description %}{% endblock head_description %}">
	<meta name="keywords" content="{% block head_keywords %}{% endblock head_keywords %}">
	
	<link rel="stylesheet" href="/assets/styles/app.css">
	
	{% block head_extra %}{% endblock head_extra %}
	
</head>
<body>
	
	{% include 'app/partials/flash.phtml' %}
	
	{% block header %}
		
		<header>
			
			<h6><a href="{{ path_for('home') }}">Logo</a></h6>
			
			<nav>
				
				<ul>
					<li><a href="{{ path_for('home') }}">Home</a></li>
					{% if auth.check %}
						<li>
							<a href="#">{{ auth.user.name }}</a>
							<ul>
								<li><a href="{{ path_for('user.profile') }}">Edit profile</a></li>
								<li><a href="{{ path_for('user.password') }}">Change password</a></li>
								<li><a href="{{ path_for('auth.signout') }}">Sign out</a></li>
							</ul>
						</li>
					{% else %}
						<li><a href="{{ path_for('auth.signup') }}">Sign up</a></li>
						<li><a href="{{ path_for('auth.signin') }}">Sign in</a></li>
					{% endif %}
				</ul>
				
			</nav>
			
		</header>
		
	{% endblock header %}
	
	{% block banner_top %}
		
		<div>Ad</div>
		
	{% endblock banner_top %}
	
	{% block body %}
		
		<main>
			
			<section>
				
				{% block content %}{% endblock content %}
				
			</section>
			
			<aside>
				
				{% block secondary %}{% endblock secondary %}
				
			</aside>
			
		</main>
		
	{% endblock body %}
	
	{% block banner_bottom %}
		
		<div>Ad</div>
		
	{% endblock banner_bottom %}
	
	{% block footer %}
		
		<footer>
			
			<p>Copyright © 2016 First Last</p>
			
		</footer>
		
	{% endblock footer %}
	
	{% block footer_extra %}{% endblock footer_extra %}
	
	<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
	<script>if(!window.jQuery){document.write('<script src="assets/plugins/jquery/jquery-3.1.1.slim.min.js"><\/script>');}</script>
	<script src="/assets/plugins/underscore/underscore-min.js"></script>
	
	<script src="/assets/scripts/app.js"></script>
	
	<script>
		
		$(function() {});
		
	</script>
	
	{% block footer_last %}{% endblock footer_last %}
	
</body>
</html>
